name: crime_alert
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.7.7
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  fluttertoast: ^8.2.8
  connectivity_plus: ^2.2.2
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^5.2.7
  path_provider: ^2.0.15
  intl: ^0.18.0
  image_picker_web: ^4.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_tts: ^3.6.3
  flutter_image_compress: ^1.1.3
  url_launcher: ^6.1.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
