// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSsiwDOtCacBnkLxhGaqtMcHmoTQM1wtQ',
    appId: '1:50633934192:web:6424d4373992826b697bb5',
    messagingSenderId: '50633934192',
    projectId: 'crimealert-d0a3f',
    authDomain: 'crimealert-d0a3f.firebaseapp.com',
    storageBucket: 'crimealert-d0a3f.firebasestorage.app',
    measurementId: 'G-MH8E40SF2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7nDe_O8_t4wT2pKT9fn863G336qcN7o',
    appId: '1:50633934192:android:1ad5eca1030b9e77697bb5',
    messagingSenderId: '50633934192',
    projectId: 'crimealert-d0a3f',
    storageBucket: 'crimealert-d0a3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhSOZopyGS-Jy6ZJSaV6p5K8eVbu34Dss',
    appId: '1:50633934192:ios:568dd74a386b4ed0697bb5',
    messagingSenderId: '50633934192',
    projectId: 'crimealert-d0a3f',
    storageBucket: 'crimealert-d0a3f.firebasestorage.app',
    iosBundleId: 'com.example.crimeAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSsiwDOtCacBnkLxhGaqtMcHmoTQM1wtQ',
    appId: '1:50633934192:web:5fd08e4f11e6f333697bb5',
    messagingSenderId: '50633934192',
    projectId: 'crimealert-d0a3f',
    authDomain: 'crimealert-d0a3f.firebaseapp.com',
    storageBucket: 'crimealert-d0a3f.firebasestorage.app',
    measurementId: 'G-M01FYYRE12',
  );
}
